document.getElementById('header-container').style.backgroundColor = '#61D747'
document.getElementsByClassName('emergency-tasks')[0].style.backgroundColor = 'pink'
document.querySelector('.no-emergency-tasks').style.backgroundColor = 'yellow'
document.querySelectorAll('.emergency-tasks h3 ')[0].style.backgroundColor = 'purple'
document.querySelectorAll('.emergency-tasks h3 ')[1].style.backgroundColor = 'purple'
document.querySelectorAll('.no-emergency-tasks h3 ')[0].style.backgroundColor = 'black'
document.querySelectorAll('.no-emergency-tasks h3 ')[1].style.backgroundColor = 'black'
document.getElementsByTagName('footer')[0].style.backgroundColor = 'green'